default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rails_development
test:
  <<: *default
  database: rails_test
production:
  <<: *default
  database: rails_production
  username: rails
  password: <%= ENV["TENANT_BUNDLE_DATABASE_PASSWORD"] %>
